# Generated by Django 5.2.15 on 2026-06-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_generationjob_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
                ('allowed_inputs', models.JSONField(blank=True, default=list)),
                ('forbidden_inputs', models.JSONField(blank=True, default=list)),
                ('audit_requirements', models.JSONField(blank=True, default=list)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('is_destructive', models.BooleanField(default=False)),
                ('is_external', models.BooleanField(default=False)),
                ('safe_roots', models.JSONField(blank=True, default=list)),
                ('is_enabled', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
