# Generated by Django 5.2.15 on 2026-06-09 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tooldefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolExecutionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_inputs', models.JSONField(blank=True, default=dict)),
                ('decision_message', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_confirmation', 'Awaiting confirmation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed')], db_index=True, default='pending', max_length=32)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_execution_requests', to='core.telegramuser')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_requests', to='core.tooldefinition')),
            ],
        ),
    ]
