# Generated by Django 5.2.15 on 2026-06-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_toolexecutionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='priority',
            field=models.IntegerField(db_index=True, default=100),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='requested_executor',
            field=models.CharField(choices=[('local_gpu', 'Local GPU'), ('cloud', 'Cloud')], db_index=True, default='local_gpu', max_length=32),
        ),
    ]
